# Generated by Django 5.1.5 on 2025-04-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
