# Generated by Django 5.1.5 on 2025-03-27 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0003_alter_moduleformation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='formation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programmeTalent.formation'),
        ),
    ]
